import { execFileSync } from "node:child_process";

import { describe, expect, it } from "vitest";

import { createTempRepoFixture } from "./_helpers/temp-repo-fixture.mjs";

function makeFixture() {
  const fixture = createTempRepoFixture({
    prefix: "fx-vitest-framework-surfaces-",
    packageJson: {
      name: "framework-resource-fixture",
      private: true,
      type: "module",
      devDependencies: { "@storybook/react": "^8.0.0" },
      dependencies: { "@strapi/strapi": "^5.0.0" },
    },
  });

  fixture.write(
    "src/Button.stories.tsx",
    'export default { title: "Button" };\n',
  );
  fixture.write(
    "src/api/article/controllers/article.ts",
    "export default { find() {} };\n",
  );
  fixture.write(
    "types/generated/contentTypes.d.ts",
    "export interface Article {}\n",
  );
  fixture.write("public/vendor.js", "window.vendor = true;\n");
  fixture.write("src/app.bundle.js", "export const bundled = true;\n");
  fixture.write(
    "src/emscripten-bindings.js",
    "// @ts-nocheck\n// Generated by Emscripten\n",
  );
  fixture.write("templates/controller.ts.hbs", "export default {};\n");
  fixture.write(
    "resources/codemods/rename/input.ts",
    "export const input = true;\n",
  );
  fixture.write("src/plain.ts", "export const plain = true;\n");

  return fixture;
}

function runProducer() {
  const fixture = makeFixture();
  try {
    execFileSync(
      process.execPath,
      [
        "build-framework-resource-surfaces.mjs",
        "--root",
        fixture.root,
        "--output",
        fixture.output,
      ],
      {
        cwd: process.cwd(),
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      },
    );
    return fixture.readJson("framework-resource-surfaces.json", {
      from: "output",
    });
  } finally {
    fixture.cleanup();
  }
}

function runAudit() {
  const fixture = makeFixture();
  try {
    execFileSync(
      process.execPath,
      [
        "audit-repo.mjs",
        "--root",
        fixture.root,
        "--output",
        fixture.output,
        "--profile",
        "quick",
      ],
      {
        cwd: process.cwd(),
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      },
    );
    return {
      manifest: fixture.readJson("manifest.json", { from: "output" }),
      surfaces: fixture.readJson("framework-resource-surfaces.json", {
        from: "output",
      }),
      summary: fixture.read("audit-summary.latest.md", { from: "output" }),
    };
  } finally {
    fixture.cleanup();
  }
}

describe("build framework resource surfaces producer", () => {
  it("BFRS1. producer writes framework-resource-surfaces artifact", () => {
    const artifact = runProducer();

    expect(artifact.schemaVersion).toBe("framework-resource-surfaces.v1");
    expect(artifact.policyVersion).toBe("framework-resource-surface-policy-v1");
    expect(artifact.summary.totalFilesWithSurfaces).toBe(8);
    expect(artifact.summary.byLane["framework-dispatch-entry"]).toBe(2);
    expect(artifact.summary.byLane["bundled-build-artifact"]).toBe(3);
    expect(artifact.summary.byLane["generated-declaration-surface"]).toBe(1);
    expect(artifact.summary.byLane["scaffold-template-resource"]).toBe(1);
    expect(artifact.summary.byLane["codemod-resource"]).toBe(1);
    expect(artifact.summary.byCapabilityPack["framework.storybook"]).toBe(1);
    expect(artifact.summary.byCapabilityPack["framework.strapi"]).toBe(1);
    expect(
      artifact.summary.byCapabilityPack["surface.bundled-build-artifact"],
    ).toBe(3);
    expect(
      artifact.summary.byCapabilityPack["surface.generated-declaration"],
    ).toBe(1);
    expect(artifact.summary.byCapabilityPack["surface.scaffold-template"]).toBe(
      1,
    );
    expect(artifact.summary.byCapabilityPack["surface.codemod-resource"]).toBe(
      1,
    );
    expect(artifact.files).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          file: "src/Button.stories.tsx",
          surfaceLanes: expect.arrayContaining([
            expect.objectContaining({ capabilityPack: "framework.storybook" }),
          ]),
        }),
        expect.objectContaining({
          file: "templates/controller.ts.hbs",
          surfaceLanes: expect.arrayContaining([
            expect.objectContaining({
              capabilityPack: "surface.scaffold-template",
            }),
          ]),
        }),
      ]),
    );
  });

  it("BFRS2. audit-repo runs producer and surfaces manifest/summary metadata", () => {
    const { manifest, surfaces, summary } = runAudit();

    expect(manifest.commandsRun).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          step: "build-framework-resource-surfaces.mjs",
          status: "ok",
        }),
      ]),
    );
    expect(manifest.artifactsProduced).toContain(
      "framework-resource-surfaces.json",
    );
    expect(manifest.frameworkResourceSurfaces?.totalFilesWithSurfaces).toBe(8);
    expect(
      manifest.frameworkResourceSurfaces?.byLane?.["framework-dispatch-entry"],
    ).toBe(2);
    expect(surfaces.summary.totalFilesWithSurfaces).toBe(8);
    expect(summary).toMatch(/Framework\/resource surfaces: 8 files/);
    expect(summary).toMatch(/framework-resource-surfaces\.json/);
  }, 15_000);
});
