import { describe, expect, it } from "vitest";

import {
  FRAMEWORK_RESOURCE_SURFACE_POLICY_VERSION,
  classifyFrameworkResourceSurfaces,
} from "../_lib/framework-resource-surfaces.mjs";

function lanes(artifact, file) {
  return (
    artifact.files.find((entry) => entry.file === file)?.surfaceLanes ?? []
  );
}

function firstLane(artifact, file) {
  const lane = lanes(artifact, file)[0];
  expect(lane, `expected surface lane for ${file}`).toBeTruthy();
  return lane;
}

describe("framework resource surfaces", () => {
  it("FRS1. classifies grounded Storybook and Strapi dispatch surfaces", () => {
    const artifact = classifyFrameworkResourceSurfaces({
      root: "/repo",
      files: [
        "src/Button.stories.tsx",
        "src/api/article/controllers/article.ts",
        "src/api/article/routes/article.ts",
        "src/plain.ts",
      ],
      packageRecords: [
        {
          relRoot: ".",
          packageJson: {
            devDependencies: { "@storybook/react": "^8.0.0" },
            dependencies: { "@strapi/strapi": "^5.0.0" },
          },
        },
      ],
    });

    expect(artifact.schemaVersion).toBe("framework-resource-surfaces.v1");
    expect(artifact.policyVersion).toBe(
      FRAMEWORK_RESOURCE_SURFACE_POLICY_VERSION,
    );

    expect(firstLane(artifact, "src/Button.stories.tsx")).toEqual({
      lane: "framework-dispatch-entry",
      capabilityPack: "framework.storybook",
      confidence: "grounded",
      framework: "storybook",
      reason: "storybook-story-file",
      defaultAction: "review-hint",
      affectsAbsenceClaims: true,
      evidence: [
        { kind: "dependency", field: "devDependencies.@storybook/react" },
        { kind: "path-convention", matched: "*.stories.*" },
      ],
    });

    const controller = firstLane(
      artifact,
      "src/api/article/controllers/article.ts",
    );
    expect(controller).toMatchObject({
      lane: "framework-dispatch-entry",
      capabilityPack: "framework.strapi",
      confidence: "grounded",
      framework: "strapi",
      reason: "strapi-filesystem-api",
    });

    const route = firstLane(artifact, "src/api/article/routes/article.ts");
    expect(route).toMatchObject({
      capabilityPack: "framework.strapi",
      framework: "strapi",
      confidence: "grounded",
    });

    expect(lanes(artifact, "src/plain.ts")).toHaveLength(0);
    expect(artifact.summary.totalFilesWithSurfaces).toBe(3);
    expect(artifact.summary.byLane["framework-dispatch-entry"]).toBe(3);
    expect(artifact.summary.byCapabilityPack["framework.storybook"]).toBe(1);
    expect(artifact.summary.byCapabilityPack["framework.strapi"]).toBe(2);
    expect(artifact.summary.byConfidence.grounded).toBe(3);
  });

  it("FRS2. keeps path-only framework shapes as review-visible, not grounded", () => {
    const artifact = classifyFrameworkResourceSurfaces({
      root: "/repo",
      files: [
        "src/Button.stories.tsx",
        "src/api/article/controllers/article.ts",
      ],
      packageRecords: [{ relRoot: ".", packageJson: { dependencies: {} } }],
    });

    for (const file of [
      "src/Button.stories.tsx",
      "src/api/article/controllers/article.ts",
    ]) {
      const lane = firstLane(artifact, file);
      expect(lane.lane).toBe("framework-dispatch-entry");
      expect(lane.confidence).toBe("path-shaped-review");
      expect(lane.defaultAction).toBe("review-hint");
    }
  });

  it("FRS3. classifies generated declarations, bundles, templates, and codemod resources", () => {
    const artifact = classifyFrameworkResourceSurfaces({
      root: "/repo",
      files: [
        "types/generated/contentTypes.d.ts",
        "public/vendor.js",
        "dist/app.bundle.js",
        "dist/app.min.js",
        "src/emscripten-bindings.js",
        "templates/component.tsx.hbs",
        "resources/codemods/rename/input.ts",
        "__testfixtures__/fixture.ts",
      ],
      packageRecords: [{ relRoot: ".", packageJson: {} }],
      contentsByFile: {
        "src/emscripten-bindings.js":
          "// @ts-nocheck\n// Generated by Emscripten\nexport const Module = {};\n",
      },
    });

    expect(
      firstLane(artifact, "types/generated/contentTypes.d.ts"),
    ).toMatchObject({
      lane: "generated-declaration-surface",
      capabilityPack: "surface.generated-declaration",
      confidence: "generated-output-review",
    });

    for (const file of [
      "public/vendor.js",
      "dist/app.bundle.js",
      "dist/app.min.js",
    ]) {
      expect(firstLane(artifact, file)).toMatchObject({
        lane: "bundled-build-artifact",
        capabilityPack: "surface.bundled-build-artifact",
        confidence: "generated-output-review",
      });
    }

    expect(firstLane(artifact, "src/emscripten-bindings.js")).toMatchObject({
      lane: "bundled-build-artifact",
      capabilityPack: "surface.bundled-build-artifact",
      reason: "emscripten-generated-header",
    });
    expect(firstLane(artifact, "templates/component.tsx.hbs")).toMatchObject({
      lane: "scaffold-template-resource",
      capabilityPack: "surface.scaffold-template",
    });
    expect(
      firstLane(artifact, "resources/codemods/rename/input.ts"),
    ).toMatchObject({
      lane: "codemod-resource",
      capabilityPack: "surface.codemod-resource",
    });
    expect(firstLane(artifact, "__testfixtures__/fixture.ts")).toMatchObject({
      lane: "codemod-resource",
      capabilityPack: "surface.codemod-resource",
    });

    expect(artifact.summary.totalFilesWithSurfaces).toBe(8);
    expect(artifact.summary.byLane["bundled-build-artifact"]).toBe(4);
    expect(artifact.summary.byLane["codemod-resource"]).toBe(2);
    expect(
      artifact.summary.byCapabilityPack["surface.bundled-build-artifact"],
    ).toBe(4);
    expect(artifact.summary.byCapabilityPack["surface.codemod-resource"]).toBe(
      2,
    );
    expect(
      artifact.summary.byCapabilityPack["surface.generated-declaration"],
    ).toBe(1);
    expect(artifact.summary.byCapabilityPack["surface.scaffold-template"]).toBe(
      1,
    );
  });

  it("FRS4. output is deterministic and sorted by file path", () => {
    const artifact = classifyFrameworkResourceSurfaces({
      root: "/repo",
      files: [
        "templates/z.hbs",
        "src/B.stories.tsx",
        "resources/codemods/a.ts",
      ],
      packageRecords: [
        {
          relRoot: ".",
          packageJson: { devDependencies: { storybook: "^8.0.0" } },
        },
      ],
    });

    expect(artifact.files.map((entry) => entry.file)).toEqual([
      "resources/codemods/a.ts",
      "src/B.stories.tsx",
      "templates/z.hbs",
    ]);
  });
});
